### ISSUE TITLE
How to obtain the threshold mentioned in the paper

### ISSUE THREAD

**Issue by wuheng793** [yawenouyang/AIK#1]
The threshold is a very important value to identify as an OOD intention in the paper, but I didn't see it in the code. Can you tell me whether the threshold is reflected in the code? If not, how can I get this threshold?

**Comment by yawenouyang** [comment]
hi, we can adjust the threshold based on our need. for example, the picked threshold could meet the id (or ood) recall rate is 95%. about code, see here https://github.com/yawenouyang/AIK/blob/933096476f7f23990b70903a707494f6a1d5b7db/util/ood_method.py#L22

**Comment by wuheng793** [comment]
Thank you for your reply. I want to  confirm that the threshold is derived from the validation set and subsequently apply it to the test set. Is there any problem with this process? In addition, I would like to know that the current setting of the paper is only to detect OOD intentions, which is equivalent to a binary-classification problem. However, why not extend your method with simple modifications to open set recognition, detecting unknown intents based on correctly identifying known categories?
